import { Inter } from "next/font/google";
import "./globals.css";
import Main from "./components/main_page/page";
import Footer from "./components/main_page/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "k-HUB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Main />
        {children}
        <Footer />
      </body>
    </html>
  );
}
